version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: spaceapps_db
    ports:
      - "5432:5432"
